---
title: "Workshop5-ggplot2"
author: "Meral Erdogan"
date: "18 08 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
library(lubridate)

theme_set(theme_light())

data(mpg)
mpg%>%ggplot(
 aes(x=displ,
     y=hwy,
     color=class,
     size=cyl,
     shape=drv
     )
)+
  geom_point()



```




```{r}


data(mpg)
mpg%>%ggplot(
 aes(x=year,
     y=cty,
     color=trans,
     size=cyl,
     shape=fl
     )
)+
  geom_boxplot()





```




```{r}

data(mpg)
mpg%>%ggplot(
 aes(x=manufacturer,
     y=displ,
     fill=cty,
     size=hwy,
     shape=drv
     )
)+
  geom_line()





```


```{r}


data(mpg)
mpg%>%ggplot(
 aes(x=year,
     y=cty,
     color=trans,
     size=cyl,
     shape=fl
     )
)+
  geom_line()


```


```{r}


data(mpg)
mpg%>%ggplot(
 aes(x=class,
     y=displ,
     color=trans,
     size=cyl,
     shape=fl
     )
)+
  geom_line()



```




```{r}

data(mpg)
mpg%>%ggplot(
 aes(x=displ,
     y=hwy,
     color=class)
)+
  geom_point()+
  facet_wrap(~cyl,nrow=2)


```



```{r}



survey <- survey %>%
  mutate(timestamp = mdy_hms(timestamp),
         age_category = fct_relevel(fct_reorder(how_old_are_you, parse_number(how_old_are_you)), "under 18"),
         experience_overall = str_replace(overall_years_of_professional_experience, " - ", "-"),
         experience_overall = fct_reorder(experience_overall, parse_number(experience_overall)),
         experience_in_field = str_replace(years_of_experience_in_field, " - ", "-"),
         experience_in_field = fct_reorder(experience_in_field, parse_number(experience_in_field))) %>%
  mutate(gender = fct_collapse(coalesce(gender, "Other or prefer not to answer"), "Other or prefer not to answer" = c("Other or prefer not to answer", "Prefer not to answer")),
         race = fct_lump(coalesce(race, "Other"), 4),
         age=parse_number(how_old_are_you))

survey_usd <- survey %>%
  filter(currency == "USD") %>%
  filter(annual_salary >= 5000,
         annual_salary <= 2e6) %>%
  mutate(state = str_remove(state, ", .*"))



```


